import { useId } from "react";
import { BRAND_COLORS, LOCKUP, SYMBOL, WORDMARK } from "../../brand/marks";

type Tone = "color-dark" | "color" | "white" | "ink";

/**
 * The Lanther symbol: a forward-leaning L, cut once at the heel. Paths are
 * generated by scripts/brand/build.py.
 *
 * The site uses "color-dark" (white upright, blade lit blue to violet), the
 * flat dark-colour version. "white" and "ink" are the one-colour versions.
 */
export function LogoMark({ size = 28, tone = "color-dark", className }: { size?: number; tone?: Tone; className?: string }) {
  const id = useId();
  const bodyFill = tone === "ink" || tone === "color" ? BRAND_COLORS.ink : "#FFFFFF";
  const lit = tone === "color" || tone === "color-dark";
  return (
    <svg width={size} height={size} viewBox={SYMBOL.viewBox} aria-hidden="true" className={className}>
      {lit && (
        <defs>
          <linearGradient id={`${id}-h`} x1="0" y1="48" x2="20" y2="28" gradientUnits="userSpaceOnUse">
            <stop stopColor={BRAND_COLORS.blue} />
            <stop offset="1" stopColor={BRAND_COLORS.violet} />
          </linearGradient>
        </defs>
      )}
      <path d={SYMBOL.body} fill={bodyFill} />
      <path d={SYMBOL.heel} fill={lit ? `url(#${id}-h)` : bodyFill} />
    </svg>
  );
}

/** The LANTHER wordmark. `height` is the cap height in px. */
export function Wordmark({ height = 12, color = "currentColor", className }: { height?: number; color?: string; className?: string }) {
  return (
    <svg height={height} width={(WORDMARK.width / 100) * height} viewBox={WORDMARK.viewBox} aria-hidden="true" className={className}>
      <path d={WORDMARK.d} fill={color} />
    </svg>
  );
}

/** Horizontal lockup, in the same proportions as lockup-horizontal-color-dark.svg. */
export function Logo({ className, size = 30, tone = "color-dark" }: { className?: string; size?: number; tone?: Tone }) {
  const color = tone === "ink" || tone === "color" ? BRAND_COLORS.ink : "#FFFFFF";
  return (
    <span className={`inline-flex items-center ${className ?? ""}`} style={{ gap: size * LOCKUP.gap }}>
      <LogoMark size={size} tone={tone} />
      <Wordmark height={Math.round(size * LOCKUP.cap * 10) / 10} color={color} />
      <span className="sr-only">Lanther</span>
    </span>
  );
}
