import { useId } from "react";
import { SYMBOL, SYMBOL_SMALL, WORDMARK, BRAND_COLORS } from "../../brand/marks";

type Tone = "white" | "ink" | "color-dark" | "color";

/**
 * The Lanther symbol: a tile with one tapered passage cut through it.
 * Paths are generated by scripts/brand/build.py. Below 32px the small cut is
 * used, which keeps the passage open after pixel snapping.
 */
export function LogoMark({ size = 28, tone = "white", className }: { size?: number; tone?: Tone; className?: string }) {
  const id = useId();
  const g = size <= 32 ? SYMBOL_SMALL : SYMBOL;
  const bodyFill = tone === "ink" || tone === "color" ? BRAND_COLORS.ink : "#FFFFFF";
  const lit = tone === "color" || tone === "color-dark";
  return (
    <svg width={size} height={size} viewBox={g.viewBox} aria-hidden="true" className={className}>
      {lit && (
        <defs>
          <linearGradient id={`${id}-p`} x1="18" y1="0" x2="48" y2="31" gradientUnits="userSpaceOnUse">
            <stop stopColor={BRAND_COLORS.blue} />
            <stop offset="1" stopColor={BRAND_COLORS.violet} />
          </linearGradient>
        </defs>
      )}
      <path d={g.body} fill={bodyFill} />
      {lit && <path d={g.passage} fill={`url(#${id}-p)`} />}
    </svg>
  );
}

/** The LANTHER wordmark. `height` is the cap height in px. */
export function Wordmark({ height = 12, color = "currentColor", className }: { height?: number; color?: string; className?: string }) {
  return (
    <svg
      height={height}
      width={(WORDMARK.width / 100) * height}
      viewBox={WORDMARK.viewBox}
      aria-hidden="true"
      className={className}
    >
      <path d={WORDMARK.d} fill={color} />
    </svg>
  );
}

/** Horizontal lockup. Symbol is about 1.65x the wordmark's cap height. */
export function Logo({ className, size = 26 }: { className?: string; size?: number }) {
  return (
    <span className={`inline-flex items-center text-ink ${className ?? ""}`} style={{ gap: size * 0.34 }}>
      <LogoMark size={size} />
      <Wordmark height={Math.round(size * 0.6 * 10) / 10} />
      <span className="sr-only">Lanther</span>
    </span>
  );
}
